<?php
/**
 * @file
 * Code for the IPWA_projekt  feature.
 */

include_once 'ipwa_projekt_.features.inc';


//for hiding longitude and latitude in the backend
function ipwa_projekt__form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'protagonist_node_form' || $form_id == 'projekt_node_form') {
   $form['#validate'][0] = 'ipwa_projekt__node_form_validate';
   $form['field_latitude']['#access'] = 0;
   $form['field_longitude']['#access'] = 0;
  }
 }

function ipwa_projekt__node_form_validate($form, &$form_state)
{
  if($form_state['node']->type == 'protagonist' || $form_state['node']->type == 'projekt') {
    if(!empty($form_state['values']['field_plz']['und'][0]['value'])) {
      $lat = NULL;
      $lng = NULL;
      $param[] = $form_state['values']['field_plz']['und'][0]['value'];
      $location[] = $form_state['values']['field_address']['und'][0]['value'];


      //  for providing longitude and latitude according to the plz given
      $query_param = implode(" ", $param);
      $query_param2 = implode(" ", $location);
      if(!empty($form_state['values']['field_address']['und'][0]['value'])) {
      $val_new = 'https://sg.geodatenzentrum.de/gdz_geokodierung__13dd535b-273e-b0f5-d42f-f2fa2cfa13d6/geosearch.json?query=' . $query_param .' '. urlencode($query_param2) . '&filter=typ:haus&count=1';}
      else
      {$val_new = 'https://sg.geodatenzentrum.de/gdz_geokodierung__13dd535b-273e-b0f5-d42f-f2fa2cfa13d6/geosearch.json?query=' . $query_param . '&filter=typ:haus&count=1';}
      $json = file_get_contents($val_new);
      $json = json_decode($json);
      $lng = $json->features[0]->geometry->coordinates[0];
      $lat = $json->features[0]->geometry->coordinates[1];

      //changing the values of latitude and longitude
      $form['field_longitude']['#parents'] = array('field_longitude', 'und', '0', 'value');
      form_set_value($form['field_longitude'], $lng, $form_state);
      $form['field_latitude']['#parents'] = array('field_latitude', 'und', '0', 'value');
      form_set_value($form['field_latitude'], $lat, $form_state);

    }
      //validating if longitude and latitude is present or not
      if(is_null($lat) && is_null($lng)) {
        form_set_error('plz',t('Please enter a valid plz'));
      }
    }



}
