<?php
/**
 * @file
 * Drupal needs this blank file.
 */
/**
 * Implements hook_block_info(). footer blocks genrated in code
 */
function ipwa_base_block_info() {
    $blocks = array();
    $blocks['footer_block_icons'] = array(
        'info' => t('footer icon links'),
    );
    return $blocks;
}
/**
 * Implements hook_block_view().
 */
function ipwa_base_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'footer_block_icons':
            $block['subject'] = 'Gefördert durch';
            $block['content'] = show_footer_block_icons();
            break;
            $block['#action'] = $base_url;
    }
    return $block;
}
function show_footer_block_icons() {
    global $base_path;
    $output_icons='<div id=footer-icons-images>
                   <div>
                     <img src="'.$base_path.'profiles/ipwa/themes/ipwa/images/EU Logo.png" alt="EFRE Foerderhinweis deutsch farbig">
                   </div>
                   <div>
                     <img src="'.$base_path.'profiles/ipwa/themes/ipwa/images/EFRE.NRW.png" alt="Ziel2NRW_RGB_1809">
                   </div>
                   <div>
                     <img src="'.$base_path.'profiles/ipwa/themes/ipwa/images/MWEI.png" alt="NRW_MWEIMH_RGB">
                   </div>
                 </div>';

    return $output_icons;

}