<?php
/**
 * @file
 * ipwa_termin_.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function ipwa_termin__field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_zeit'.
  $field_bases['field_zeit'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_zeit',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_zus_tzliche_informationen_'.
  $field_bases['field_zus_tzliche_informationen_'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_zus_tzliche_informationen_',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
