<?php
/**
 * @file
 * Code for the IPWA Newsletter feature.
 */

include_once 'ipwa_newsletter.features.inc';

/**
 * Implements hook_block_info().
 */
function ipwa_newsletter_block_info() {
  $blocks['newsletter_subscription_block'] = array(
    'info' => t('Newsletter Subscription Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ipwa_newsletter_block_view($delta = '') {
  $block = '';
  switch ($delta) {
    case 'newsletter_subscription_block':
      $block['subject'] = t('Newsletter-Abonnement');
      $content = drupal_get_form('ipwa_newsletter_block_form');
      $block['content'] = drupal_render($content);
      break;
  }
  return $block;
}

/**
 * Implements hook_block_form().
 */
function ipwa_newsletter_block_form($form, &$form_state) {
  global $base_url;
  $form['newsletter'] = array(
    '#title' => '  ',
    '#type' => 'textfield',
    '#required' => False,
    '#attributes' => array('placeholder'=> 'E-Mail Adresse eintragen'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('weiter zu Schritt 2'),
  );
  $form['#action'] = $base_url. '/';
  $form['#submit'][] = 'ipwa_newsletter_custom_form_submit';
  return $form;
}

/**
 * Implements hook_form_submit().
 */
function ipwa_newsletter_custom_form_submit($form, &$form_state){
  global $base_url;
  $form_state['redirect'] = $base_url . '/content/newsletter-registrierung?subscription-e-mail='.$form_state['values']['newsletter'];
}

/**
 * Implements hook_form_FORM_alter().
 */
function ipwa_newsletter_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'webform_client_form_125'){
    global $base_url;
    $node_title=(node_load(1)->title);
    $form['submitted']['datenschutzhinweise']['#options'][0] = '<div class="privacy-policy-title">Ich habe die <a href="'.$base_url.'/artikel/'.$node_title.'" target="_blank">Datenschutz</a> gelesen und stimme ihnen zu.*';
    if(isset($_REQUEST['subscription-e-mail'])){
      $form['submitted']['ihre_e_mail_address']['#default_value'] = $_REQUEST['subscription-e-mail'];
    }
    $form['#submit'][] = 'ipwa_newsletter_webform_client_form_submit';
  }
  if($form_id == 'simplenews_node_form'){
    $form['field_simplenews_term']['#access'] = 0;
  }
}

/**
 * Implements hook_form_submit().
 */
function ipwa_newsletter_webform_client_form_submit($form, &$form_state){
  if(isset($form['submitted']['ihre_e_mail_address']['#value'])){
    $mail = $form['submitted']['ihre_e_mail_address']['#value'];
    simplenews_subscribe_user($mail, 48, $confirm = TRUE, $source = 'action', NULL);
  }
}
