<?php
/**
 * @file
 * Code for the webform feature.
 */

include_once 'ipwa_webform.features.inc';
function ipwa_form_webform_node_form_alter( &$form, &$form_state,$form_id ){
  honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));
}

function ipwa_webform_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'webform_client_form_123') {
    $form['#node']->content['field_pflichtfeldhinweis']['0']['#markup'] ='<span class="required-hint">'.'Die mit * markierten Felder sind verpflichtend und müssen ausgefüllt werden.'.'</span>';
  }else{
    $form['#node']->content['field_pflichtfeldhinweis']['0']['#markup'] = '<span class="required-hint"><h3>' . 'Die mit * markierten Felder des E-Mail-Formulars sind Pflichtfelder.' . '</h3></span>';
  }
}