<?php
/**
 * @file
 * ipwa_topic.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function ipwa_topic_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'taxonomy_term-themenzuweisung-field_anzuzeigende_seitenmodule'.
  $field_instances['taxonomy_term-themenzuweisung-field_anzuzeigende_seitenmodule'] = array(
    'bundle' => 'themenzuweisung',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'paragraphs',
        'settings' => array(
          'view_mode' => 'full',
        ),
        'type' => 'paragraphs_view',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_anzuzeigende_seitenmodule',
    'label' => 'Anzuzeigende Seitenmodule (Paragraphen)',
    'required' => 0,
    'settings' => array(
      'add_mode' => 'select',
      'allowed_bundles' => array(
        'flie_text_bereich' => -1,
        'flie_text_mit_bild_links' => -1,
        'flie_text_mit_bild_rechts' => -1,
        'frontpage_map_teaser_paragraph' => -1,
        'topic_teaser_paragraph' => -1,
        'views' => -1,
      ),
      'bundle_weights' => array(
        'flie_text_bereich' => 2,
        'flie_text_mit_bild_links' => 3,
        'flie_text_mit_bild_rechts' => 4,
        'frontpage_map_teaser_paragraph' => 5,
        'topic_teaser_paragraph' => 6,
        'views' => 7,
      ),
      'default_edit_mode' => 'open',
      'title' => 'Paragraph',
      'title_multiple' => 'Paragraphs',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'paragraphs',
      'settings' => array(),
      'type' => 'paragraphs_embed',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'taxonomy_term-themenzuweisung-field_bild'.
  $field_instances['taxonomy_term-themenzuweisung-field_bild'] = array(
    'bundle' => 'themenzuweisung',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'file_image_formatters',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'file_image_image',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_bild',
    'label' => 'Icon',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'public' => 'public',
        ),
        'allowed_types' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_default--media_browser_1' => 0,
          'media_default--media_browser_my_files' => 0,
          'upload' => 0,
        ),
      ),
      'type' => 'media_generic',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-themenzuweisung-field_kurztext'.
  $field_instances['taxonomy_term-themenzuweisung-field_kurztext'] = array(
    'bundle' => 'themenzuweisung',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_kurztext',
    'label' => 'Kurztext',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'taxonomy_term-themenzuweisung-field_untertitel'.
  $field_instances['taxonomy_term-themenzuweisung-field_untertitel'] = array(
    'bundle' => 'themenzuweisung',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_untertitel',
    'label' => 'Untertitel',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Anzuzeigende Seitenmodule (Paragraphen)');
  t('Icon');
  t('Kurztext');
  t('Untertitel');

  return $field_instances;
}
