<?php
/**
 * @file
 * Code for the IPWA_förderbekanntmachung feature.
 */

include_once 'ipwa_f_rderbekanntmachung.features.inc';

/**
 * Implements hook_node_view().
 *
 * @params $node
 *
 */

//for showing field_datum with bis-auf-weitres , if ticked bis-auf-weitres will be shown else datum will be shown.
//@see https://issues.init.de/browse/IPWA4-221

function ipwa_f_rderbekanntmachung_node_view($node, $view_mode, $langcode)
{
  // for CT Förderbekanntmachung
  if ($node->type == 'f_rderbekanntmachung' && !empty($node->content['field_bis_auf_weiteres'])) {
    if ($node->content['field_bis_auf_weiteres']['#items'][0]['value'] == 1) {
      $node->content['field_bis_auf_weiteres']['#title'] = "Stichtag:";
      $node->content['field_bis_auf_weiteres'][0]['#markup'] = '<div class="field field-name-field-datum field-type-datetime field-label-inline clearfix"><div class="field-label">Stichtag:</div>&nbsp;Bis auf Weiteres</div>';
      $node->content['field_datum']['#weight'] = 21;
    }
    if ($node->content['field_bis_auf_weiteres']['#items'][0]['value'] == 0) {
      $node->content['field_bis_auf_weiteres']['#title'] = "Stichtag:";
      $node->content['field_bis_auf_weiteres'][0]['#markup'] ='<div class="field field-name-field-datum field-type-datetime field-label-inline clearfix"><div class="field-label">Stichtag:</div>&nbsp;'.$node->content['field_datum'][0]['#markup'].'</div>';
      $node->content['field_bis_auf_weiteres']['#weight'] = 21;
    }
    $node->content['field_datum']['#access'] = 0;
  }
}