<?php
/**
 * @file
 * Code for the IPWA_förderbekanntmachung feature.
 */

include_once 'ipwa_f_rderbekanntmachung.features.inc';

/**
 * Implements hook_node_view().
 *
 * @params $node
 *
 */
function ipwa_f_rderbekanntmachung_node_view($node, $view_mode, $langcode) {
  // for CT Förderbekanntmachung
  if ($node->type == 'f_rderbekanntmachung' && !empty($node->content['field_bis_auf_weiteres'])) {
    if ($node->content['field_bis_auf_weiteres']['#items'][0]['value'] == 1) {
      if (empty($node->content['field_stichtag'])) {
        $node->content['field_stichtag']['#title'] = "Stichtag";
        $node->content['field_stichtag'][0]['#markup'] = '<div class="field field-name-field-stichtag field-type-datetime field-label-inline clearfix"><div class="field-label">Stichtag:</div>&nbspBis auf Weiteres</div>';
        $node->content['field_stichtag']['#weight'] = 17;
      } else {
        if (!empty($node->content['field_stichtag'])) {
          $node->content['field_stichtag'][0]['#markup'] = 'Bis auf Weiteres';
        } else {
          $node->content['field_stichtag']['#access'] = 0;
        }
      }
    }
    $node->content['field_bis_auf_weiteres']['#access'] = 0;
  }
}