<?php
/**
 * @file
 * Code for the IPWA_förderbekanntmachung feature.
 */

include_once 'ipwa_f_rderbekanntmachung.features.inc';

/**
 * Implements hook_node_view().
 *
 * @params $node
 *
 */
function ipwa_f_rderbekanntmachung_node_view($node, $view_mode, $langcode)
{//for CT Förderbekanntmachung
  if ($node->type == 'f_rderbekanntmachung' && !empty($node->content['field_bis_auf_weiteres'])) {
    //embbedding date in stichtag field if date not empty
    $node->content['field_bis_auf_weiteres'][0]['#markup']= !empty($node->content['field_datum'])? $node->content['field_datum'][0]['#markup'] : ' ';
    //replacing datum with text if checkbox marked
    if($node->content['field_bis_auf_weiteres']['#items'][0]['value'] == 1) {
      if(!empty($node->content['field_datum'])) {
        $node->content['field_bis_auf_weiteres'][0]['#markup'] = $node->content['field_datum'][0]['#markup'];
        $node->content['field_datum'][0]['#markup'] = 'bis auf wietres' ;
      }
      //adjusting datum and stichtag when datum is empty
      if (empty($node->content['field_datum'])) {
        $node->content['field_datum'][0]['#markup']= 'Stichtag:bis auf wietres' ;
        $node->content['field_datum']['#weight'] = 11;
        $node->content['field_bis_auf_weiteres'][0]['#markup'] = ' ';
      }
    }
  }
}